# Generated by Django 3.1.4 on 2020-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201228_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Man', 'Мужской пол'), ('Woman', 'Женский пол')], max_length=11, verbose_name='Выбор пола'),
        ),
    ]
