# Generated by Django 3.1.4 on 2020-12-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news_shop_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
